### PR TITLE
Support IQ4_XS dequantize

### PR DESCRIPTION
**Pull request by sayap**
From my testing, the IQ4_XS quant of deepseek coder v2 has noticeably better quality than the Q3_K quants, while still can fit into 128GB of DRAM, unlike the Q4_K quants.

### CODE REVIEW

**Comment by ThomasBaruzier** [comment]
Trying this PR, got unlucky:

```python
$ python -m ktransformers.local_chat --model_path deepseek-ai/DeepSeek-V2-Chat-0628 --gguf_path DeepSeek-V2-Chat-0628-IQ4-XS --cpu_infer 30

Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "/storage/ai/envs/ktransformers/lib/python3.12/site-packages/ktransformers/local_chat.py", line 159, in <module>
    fire.Fire(local_chat)
  File "/storage/ai/envs/ktransformers/lib/python3.12/site-packages/fire/core.py", line 143, in Fire
    component_trace = _Fire(component, args, parsed_flag_args, context, name)
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/storage/ai/envs/ktransformers/lib/python3.12/site-packages/fire/core.py", line 477, in _Fire
    component, remaining_args = _CallAndUpdateTrace(
                                ^^^^^^^^^^^^^^^^^^^^
  File "/storage/ai/envs/ktransformers/lib/python3.12/site-packages/fire/core.py", line 693, in _CallAndUpdateTrace
    component = fn(*varargs, **kwargs)
                ^^^^^^^^^^^^^^^^^^^^^^
  File "/storage/ai/envs/ktransformers/lib/python3.12/site-packages/ktransformers/local_chat.py", line 106, in local_chat
    optimize_and_load_gguf(model, optimize_rule_path, gguf_path, config)
  File "/storage/ai/envs/ktransformers/lib/python3.12/site-packages/ktransformers/optimize/optimize.py", line 129, in optimize_and_load_gguf
    load_weights(module, gguf_loader)
  File "/storage/ai/envs/ktransformers/lib/python3.12/site-packages/ktransformers/util/utils.py", line 83, in load_weights
    load_weights(child, gguf_loader, prefix+name+".")
  File "/storage/ai/envs/ktransformers/lib/python3.12/site-packages/ktransformers/util/utils.py", line 85, in load_weights
    module.load()
  File "/storage/ai/envs/ktransformers/lib/python3.12/site-packages/ktransformers/operators/base_operator.py", line 60, in load
    utils.load_weights(child, self.gguf_loader, self.key+".")
  File "/storage/ai/envs/ktransformers/lib/python3.12/site-packages/ktransformers/util/utils.py", line 83, in load_weights
    load_weights(child, gguf_loader, prefix+name+".")
  File "/storage/ai/envs/ktransformers/lib/python3.12/site-packages/ktransformers/util/utils.py", line 81, in load_weights
    load_cur_state_dict(module, gguf_loader, prefix)
  File "/storage/ai/envs/ktransformers/lib/python3.12/site-packages/ktransformers/util/utils.py", line 71, in load_cur_state_dict
    weights = gguf_loader.load_gguf_tensor(translated_key, device = device).to(dtype = target_dtype)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/storage/ai/envs/ktransformers/lib/python3.12/site-packages/ktransformers/util/custom_gguf.py", line 283, in load_gguf_tensor
    raise NotImplementedError(f"ggml_type {ggml_type} not implemented")
NotImplementedError: ggml_type 23 not implemented
```

**Comment by sayap** [comment]
Great :)

Btw, I just realized that 128GB of DRAM is actually enough for the Q4_K_S quant, which has slightly better quality than IQ4_XS.

**Comment by ThomasBaruzier** [comment]
> Great :)
> 
> Btw, I just realized that 128GB of DRAM is actually enough for the Q4_K_S quant, which has slightly better quality than IQ4_XS.

I still don't understand why the Q4_K_M works very slowly on 128GB RAM + 24GB VRAM as its size is 133GB. There should be around 19GB of free space for context and OS after loading the model, right?

**Comment by sayap** [comment]
With Q4_K_M, I can see the `kswapd0` process being quite active in `top` output, and there are a lot of disk read activity in the `vmstat 1`  output, e.g.
```
# during prefill
procs -----------memory---------- ---swap-- -----io---- -system-- -------cpu-------
 r  b   swpd   free   buff  cache   si   so    bi    bo   in   cs us sy id wa st gu
 6  3      0 289244  11940 126919688    0    0 629864     0 67690 8384 41  5 49  6  0  0
 9  0      0 327360  11940 126874760    0    0 506028     0 74559 7588 42  3 50  4  0  0
 4  4      0 285072  11940 126927636    0    0 666304     0 80420 11166 40  4 50  6  0  0
 5  4      0 256908  11940 126962388    0    0 1270196     0 111297 20141 29  5 49 17  0  0
 8  0      0 393460  11948 126828420    0    0 1241244    20 119699 20492 29  7 47 17  0  0
 8  1      0 324772  11948 126889052    0    0 757848     0 88407 12399 38  4 51  8  0  0
 6  3      0 446696  11948 126755172    0    0 1162144     0 117587 16711 31  5 49 15  0  0
...

# during decode
procs -----------memory---------- ---swap-- -----io---- -system-- -------cpu-------
 r  b   swpd   free   buff  cache   si   so    bi    bo   in   cs us sy id wa st gu
10  0      0 309680   1760 126875172    0    0 213236     0 50849 28478 42  4 43 11  0  0
 8  0      0 356932   1756 126838984    0    0 300644     0 60901 21647 42  4 44 11  0  0
 8  1      0 287424   1752 126911680    0    0 204052     0 30458 9555 48  2 44  5  0  0
10  0      0 284936   1748 126915004    0    0 143544     0 27526 7944 49  2 45  4  0  0
 9  0      0 415712   1744 126793764    0    0 431616     0 78055 12728 43  4 44 10  0  0
 9  0      0 384060   1740 126790948    0    0 276432     0 47443 9688 46  3 45  7  0  0
 2  7      0 314216   1736 126873164    0    0 292808     0 38419 9919 46  3 45  7  0  0
...
```
I guess 128GB RAM is just not enough to hold the weights.

**Pull request merged**
